project_id = "nfmkqrtfjrqqcraslahm"

[functions.send-emails]
verify_jwt = false

[functions.auth-helpers]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.generate-customer-insights]
verify_jwt = true